### ISSUE TITLE
Python 3.10 ImportError

### ISSUE THREAD

**Issue by kfarwell** [uploadcare/migro#79]
### Describe the bug

On Python 3.10, migro throws an error and doesn't upload anything. No problem on 3.7.

To reproduce:

`migro <PUBLIC_KEY> <INPUT_FILE>`

Or just:

`migro`

Same error.

### Expected behavior

My images are uploaded without error ;)

### Code / screenshots

```
Traceback (most recent call last):
  File "/home/kyle/.local/bin/migro", line 5, in <module>
    from migro.cli import cli
  File "/home/kyle/.local/lib/python3.10/site-packages/migro/cli.py", line 22, in <module>
    from migro.uploader.worker import Uploader, Events
  File "/home/kyle/.local/lib/python3.10/site-packages/migro/uploader/worker.py", line 16, in <module>
    from migro.uploader.utils import request
  File "/home/kyle/.local/lib/python3.10/site-packages/migro/uploader/utils.py", line 12, in <module>
    from aiohttp import ClientSession, TCPConnector
  File "/home/kyle/.local/lib/python3.10/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "/home/kyle/.local/lib/python3.10/site-packages/aiohttp/client.py", line 18, in <module>
    from . import client_exceptions, client_reqrep
  File "/home/kyle/.local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 17, in <module>
    from . import hdrs, helpers, http, multipart, payload
  File "/home/kyle/.local/lib/python3.10/site-packages/aiohttp/multipart.py", line 8, in <module>
    from collections import Mapping, Sequence, deque
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

### Environment

 - Library version: migro 1.6.1 from pip
 - Language/framework version: Python 3.10.2
 - OS version: Arch Linux 5.16.9-zen1-1-zen x86_64

**Comment by rsedykh** [comment]
Was fixed in #80.

**Comment by Terbiy** [comment]
Hi! Two days ago, I've installed the 3.10.4 version of Python from [the official download page](https://www.python.org/downloads/).

When trying to run the `migro <PUBLIC_KEY> <INPUT_FILE>` command, I encountered the following error:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/migro", line 5, in <module>
    from migro.cli import cli
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/migro/cli.py", line 22, in <module>
    from migro.uploader.worker import Uploader, Events
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/migro/uploader/worker.py", line 16, in <module>
    from migro.uploader.utils import request
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/migro/uploader/utils.py", line 12, in <module>
    from aiohttp import ClientSession, TCPConnector
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/client.py", line 18, in <module>
    from . import client_exceptions, client_reqrep
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 17, in <module>
    from . import hdrs, helpers, http, multipart, payload
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/multipart.py", line 8, in <module>
    from collections import Mapping, Sequence, deque
ImportError: cannot import name 'Mapping' from 'collections' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
```

It seems like the problem remains.
